[workspace]
resolver = "2"
members = [
    "crates/oci-http-adapter",
    "crates/search-core",
    "crates/spin-http-adapter",
    "crates/static-assets",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
authors = ["Milosz Slowinski <slowinski.milosz@gmail.com>"]
license = "MIT"

[workspace.dependencies]
anyhow = "1"
movie-search-core = { path = "crates/search-core" }
static-assets = { path = "crates/static-assets" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spin-sdk = "5.2.0"
tiny_http = "0.12"
