server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = / {
    try_files /index.html =404;
  }

  location = /blog/example {
    try_files /blog/example.html =404;
  }

  location /static/ {
    try_files $uri =404;
  }
}
